### ISSUE TITLE
Ready for push

### ISSUE THREAD

**Issue by alexeiva** [cyrealtype/Podkova#1]
@m4rc1e

This is ready for push. Vmetrics identical.

<img width="1036" alt="screen shot 2016-12-16 at 4 41 56 pm" src="https://cloud.githubusercontent.com/assets/16634089/21268398/f2c7ae0a-c3ae-11e6-85a0-97bf8b49c4ca.png">
<img width="1031" alt="screen shot 2016-12-16 at 4 42 00 pm" src="https://cloud.githubusercontent.com/assets/16634089/21268399/f318d316-c3ae-11e6-8ded-c02a65939d24.png">

**Comment by m4rc1e** [comment]
Cheers man!

First thing tomorrow!

**Comment by alexeiva** [comment]
@m4rc1e updated Podkova v.2.100 is ready for a new push:
— glyph set has been expanded to GF Latin Pro, GF Cyrillic Pro
— 2 weights  (v.2.000 ) > 5 weights (v.2.100)*
— 427 glyphs (v.2.000) > 956 glyphs (v.2.100)

*What used to be Bold 700 is now ExtraBold 800

**Comment by m4rc1e** [comment]
Hey @alexeiva 

Just diffing against the currently released font. Is this weight decrease on purpose, in the bold?

![feb-01-2017 13-59-36](https://cloud.githubusercontent.com/assets/7525512/22509687/02dc59f6-e887-11e6-874b-16683b9a6055.gif)

**Comment by davelab6** [comment]
Yes I requested to move 700 to 800

**Comment by m4rc1e** [comment]
thank you!
